<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya telah membacadan_sayasetuju</name>
   <tag></tag>
   <elementGuidId>52ec0d56-9a9b-4cc6-b3ab-6dc6263caad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sayasetuju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sayasetuju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3f01257-cd94-4275-899c-233cf259f336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8f5c3362-7f4d-4ff0-ac3d-54e4dbf602cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f1aa856-fbb8-429d-8775-8d22d4f84739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sayasetuju</value>
      <webElementGuid>b8825e73-29ab-4bd7-bfe9-e18c90bf1b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sayasetuju&quot;)</value>
      <webElementGuid>e8c4e57b-6905-425f-9d18-299c109754a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sayasetuju']</value>
      <webElementGuid>ef4eef60-d793-4246-91b6-6fe79b211e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[10]/div/input</value>
      <webElementGuid>3ce8de5d-7180-4190-bbd6-a90b8bd4c991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>27577524-2bf9-48a0-9b7e-daec0c48d2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sayasetuju']</value>
      <webElementGuid>169379e1-a142-47e3-a0ce-9941e9cf7597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
