<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verifikasi</name>
   <tag></tag>
   <elementGuidId>116b5ba8-ed33-4a48-bfab-eb3e45b55c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-block.mb-5.btn-verifikasi.w-75.m-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a037afcc-8596-46b9-9fb8-82edf3e091af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96f88278-45b6-4e53-a1b1-bf2b5e811a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block mb-5 btn-verifikasi w-75 m-auto</value>
      <webElementGuid>b7aa7bf6-3d31-4c04-9ec5-49da3ae8a63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>step-3</value>
      <webElementGuid>22a14a65-d2e9-4b71-a775-b206f663c43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Verifikasi
                                    </value>
      <webElementGuid>ff43c3ae-3824-4542-af22-f080f583f68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;content justify-content-center&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-12 col-md-8&quot;]/div[@class=&quot;registration__form&quot;]/div[@class=&quot;registration__content registration__otp mb-4&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content__card rounded&quot;]/form[1]/button[@class=&quot;btn btn-primary btn-block mb-5 btn-verifikasi w-75 m-auto&quot;]</value>
      <webElementGuid>d5981319-422f-4e39-b07c-fff9788a6fd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>95159318-a5b5-41d2-83ea-b4e609ea9e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Ulang'])[1]/following::button[1]</value>
      <webElementGuid>b0084c2f-b288-4326-b1e3-cd0a8c5c99a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya Hapus'])[1]/following::button[2]</value>
      <webElementGuid>0e885e33-e8c4-4a75-b00e-0688db10d593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cookies'])[1]/preceding::button[1]</value>
      <webElementGuid>4ba36d39-9722-4b86-80eb-89a7e10d1db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari lebih lanjut'])[1]/preceding::button[1]</value>
      <webElementGuid>2fcb5e94-9a3f-4f0d-94f0-98e830b0d410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifikasi']/parent::*</value>
      <webElementGuid>031513bf-b8d3-4adb-8e21-6bf8f5b55960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>4a44f7d7-9496-4e15-a33e-69cd5c21f05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                        Verifikasi
                                    ' or . = '
                                        Verifikasi
                                    ')]</value>
      <webElementGuid>ea94e3f3-7a21-424f-a994-8ed153d77891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
