<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sebelumnya to personal form</name>
   <tag></tag>
   <elementGuidId>84efc821-a53d-4d8e-bdd1-5f89d2be1008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_prev']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>680e114e-0edc-44da-ab77-273c64e7c093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1bfa8e1f-c5d7-409e-965c-152b2e5a1e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-prev float-left</value>
      <webElementGuid>e597e0c8-bb29-4acb-b089-06b115da491a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_prev</value>
      <webElementGuid>e9d06dd4-b2b5-4d05-89a6-494ec974aff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sebelumnya</value>
      <webElementGuid>f493c668-d4f0-4b8b-861d-bf0e35963c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>prevForm(event);</value>
      <webElementGuid>e3bdb643-4a35-401a-a25e-804e04cece79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sebelumnya</value>
      <webElementGuid>97afbf22-62b0-4e08-acc0-1b477cf91b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_prev&quot;)</value>
      <webElementGuid>4ceea2a6-19bb-4ee5-8c01-e2dded637199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_prev']</value>
      <webElementGuid>f76c5502-d826-4851-b3a6-2637e1d9a35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZEE'])[2]/following::button[1]</value>
      <webElementGuid>6bf9d4ac-46de-4023-94a5-4ed7502558a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::button[1]</value>
      <webElementGuid>28c868af-a79a-4d53-b9b4-09dba8081d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::button[1]</value>
      <webElementGuid>0e8cfdcc-4f62-41bf-951e-792d0f456d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::button[2]</value>
      <webElementGuid>c54e1d63-44ff-4ebb-84c8-15591be76188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sebelumnya']/parent::*</value>
      <webElementGuid>50d89afd-d109-44c7-8cbc-411d93f303e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>579b3cba-cbef-4ccf-9ae0-63d09055dbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_prev' and @title = 'Sebelumnya' and (text() = 'Sebelumnya' or . = 'Sebelumnya')]</value>
      <webElementGuid>0ef2733f-3431-414f-ae8a-8e340d859dac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
