<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__member_birthdate</name>
   <tag></tag>
   <elementGuidId>0fe4aa70-add9-4009-82b4-dee74c3c8943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birth-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birth-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7ee2958-a2e5-4770-8db6-d469c6334af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ddc1320a-1900-4512-89cd-05d3b2faec4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birth-date</value>
      <webElementGuid>2275cefb-e80f-43a5-acb7-e1c60cfb2632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_birthdate</value>
      <webElementGuid>66327b63-9910-4acc-94e8-e0a5cceafb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Tanggal Lahir Anak Anda</value>
      <webElementGuid>18b65302-b0d9-45ca-bd4c-d39d6052cb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a76be65-69ab-4282-923b-1f39fe04d73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birth-date&quot;)</value>
      <webElementGuid>046d4dd2-0d5a-489d-b3b9-fbae78d38fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birth-date']</value>
      <webElementGuid>3768c679-a964-4b5f-8256-ba477004e5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_section_3']/div/div/input</value>
      <webElementGuid>252be4c1-4c14-4e0b-a540-6d34dce720f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>1c1a493b-ec9e-4d6b-8f8f-d9e91f527899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'birth-date' and @name = 'member_birthdate' and @placeholder = 'Masukan Tanggal Lahir Anak Anda']</value>
      <webElementGuid>7b44f935-c016-4344-aa19-bca80ed7b108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
