<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mama, Silakan Upload Struk Pembelian,_cb14af</name>
   <tag></tag>
   <elementGuidId>cc9dd7d2-378e-4b7b-ba88-64bc21f30d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e89fc961-2c66-467a-9e9f-e600776ab751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3808464a-7302-4923-98ce-f09491208ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1fddc10e-d922-431c-bb6b-069eb76aa3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_phone_number</value>
      <webElementGuid>5b5d4724-1dfc-4d6e-a235-cf24cb30a064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>36cca853-85fb-4bd6-a20d-63a10ce3e55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nomor HP Mama</value>
      <webElementGuid>e1a84794-5a15-4db1-9ec3-b5ae2aa98082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone_number&quot;)</value>
      <webElementGuid>70fee7c9-018a-4963-bbac-21109b2781c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone_number']</value>
      <webElementGuid>5b997fa2-6bd9-450b-832d-756fb2a5ce48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='upload-receipt-form']/div/div/div[3]/div/input</value>
      <webElementGuid>95e9db21-cc44-49cf-acb7-2cc077c337d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>253502fa-ff7e-4a6f-843d-930078243fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'member_phone_number' and @id = 'phone_number' and @placeholder = 'Masukkan Nomor HP Mama']</value>
      <webElementGuid>b46f1fce-872a-405a-a15f-c99a1f39bdad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
