<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__member_fullname</name>
   <tag></tag>
   <elementGuidId>e0fe8e90-8553-4930-a93c-2b8c6bdbd49a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#front-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='front-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94855efa-e1e7-4635-86f5-23df56d30e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f418fdee-27c7-42ab-b4ed-368c57d09f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>front-name</value>
      <webElementGuid>72ffed39-1bcb-4f79-a070-43c524dbfd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_fullname</value>
      <webElementGuid>d84432af-aa21-4fc4-ae46-6a1580b27243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Nama Lengkap Mama</value>
      <webElementGuid>6835a130-ed8c-4ed0-9261-a4de431675bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7efc8d8a-1e17-4b78-ad23-966dafefa21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;front-name&quot;)</value>
      <webElementGuid>d9a963a3-3282-4882-87de-3ce3912ffd04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='front-name']</value>
      <webElementGuid>8b9fca13-543e-4d94-b7ac-ec58d053aeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_section_1']/div/div[2]/input[4]</value>
      <webElementGuid>f6dfa655-3bea-42ce-b105-e6ebd034badc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[4]</value>
      <webElementGuid>05dcf968-a675-4108-a2bb-1c1dbb114787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'front-name' and @name = 'member_fullname' and @placeholder = 'Masukan Nama Lengkap Mama']</value>
      <webElementGuid>0641ec43-de6d-4da0-9381-de94fb809eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
