<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sampling_postal_code</name>
   <tag></tag>
   <elementGuidId>4319bb2a-b6cf-4b82-b260-01bdf23895b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sampling_postal_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sampling_postal_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fceba97-25bf-407b-9455-f0bd2a9c672e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c38d6164-131b-4fa3-af55-be7cfee8e9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sampling_postal_code</value>
      <webElementGuid>bcf5e4cc-601d-4683-bb92-a7b5a4ed2c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sampling_postal_code</value>
      <webElementGuid>f3ad7011-680f-4e5d-8b73-bc3cefdf18f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f460bf3c-9bc1-46e6-826b-a2c7b427e695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>043c99bc-b6f5-4b35-a6ca-ab2a0fc0044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de2119a8-7b4a-4a56-a2d6-af6956f9a71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sampling_postal_code&quot;)</value>
      <webElementGuid>9120c95b-93a9-455e-aa3e-5424582f039e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sampling_postal_code']</value>
      <webElementGuid>a410f3f7-f82f-41ca-84a0-244acb883461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_section_2']/div/div[6]/input</value>
      <webElementGuid>af498de7-0734-4ddd-a698-f42da113c844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>503d85d3-fcc8-4ef2-aaf2-e45bef93b322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sampling_postal_code' and @id = 'sampling_postal_code']</value>
      <webElementGuid>7f9ec806-97c1-45df-82fc-c22de519db42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
