<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Jakarta Utara</name>
   <tag></tag>
   <elementGuidId>e519a167-15be-4687-a3c6-425172dbfcf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-sampling_district-result-bdjh-39' and (text() = 'Jakarta Utara' or . = 'Jakarta Utara')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>257b6c7e-1237-42df-9687-707648e6585e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>14dd7a5b-771f-4904-aed1-f8c9c040f0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sampling_district-result-bdjh-39</value>
      <webElementGuid>fa371c9b-8e87-47c2-860f-3cea94129591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ab367c67-6ac3-426e-b2d4-b85285bde9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-sampling_district-result-bdjh-39</value>
      <webElementGuid>e96d0cba-bea9-4644-ac89-36ac364bcf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>116f2429-3a16-476b-a71a-67e209bc0842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jakarta Utara</value>
      <webElementGuid>d6bbcb31-afc0-444a-9d26-b0730b26241a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;select2-container select2-container--default select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--below&quot;]/span[@class=&quot;select2-results&quot;]/ul[@id=&quot;select2-sampling_district-results&quot;]/li[@id=&quot;select2-sampling_district-result-bdjh-39&quot;]</value>
      <webElementGuid>ddf76cf1-e329-4dbf-802b-8525870e859a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-sampling_district-result-bdjh-39' and (text() = 'Jakarta Utara' or . = 'Jakarta Utara')]</value>
      <webElementGuid>689ee2e7-2c96-4a97-af08-0addcaf67f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
