<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pangandaran</name>
   <tag></tag>
   <elementGuidId>41a7b235-bc2a-4096-b5f4-41281e76d9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-sampling_district-result-nfj6-78' and (text() = 'Pangandaran' or . = 'Pangandaran')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6a2a70e6-866d-47f6-a499-7dcb78beb5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>bc4d0674-7b40-4ebf-904d-d9cf46007346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sampling_district-result-nfj6-78</value>
      <webElementGuid>4f75cf2b-79ec-4fa2-909d-4d71b748c7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>76588a9f-e942-4e33-9909-6897f14fdfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-sampling_district-result-nfj6-78</value>
      <webElementGuid>7f2a16b7-04b8-4adf-afcb-7662837b42b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c44a74a-e275-4939-a0cd-1f20783e3f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pangandaran</value>
      <webElementGuid>38f3692a-7497-4362-88e0-cfd5f4bc33c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;select2-container select2-container--default select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--below&quot;]/span[@class=&quot;select2-results&quot;]/ul[@id=&quot;select2-sampling_district-results&quot;]/li[@id=&quot;select2-sampling_district-result-nfj6-78&quot;]</value>
      <webElementGuid>4914f2ed-25f1-4075-86d1-ab2e778e36d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-sampling_district-result-nfj6-78' and (text() = 'Pangandaran' or . = 'Pangandaran')]</value>
      <webElementGuid>24cd786c-f323-46f2-9d11-0a24e69eae34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
