<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Subang</name>
   <tag></tag>
   <elementGuidId>765f0633-13f9-4608-af9e-1707efe5bc78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-sampling_district-result-opca-73' and (text() = 'Subang' or . = 'Subang')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5886aada-ac5f-461d-8f52-bd87f7ad35bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>f482af40-f693-478b-8bc9-a0851602b7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sampling_district-result-opca-73</value>
      <webElementGuid>5c786565-4dfa-45a7-9ecd-aa9c4a9baa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6cdb40ce-3fbb-4323-b96a-1ab1bd213555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-sampling_district-result-opca-73</value>
      <webElementGuid>15cf853b-7941-453a-b2b4-3a6cf4806fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f95c7fdd-7671-461b-be5c-e945566315f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subang</value>
      <webElementGuid>b74498fc-2cc8-4da3-9ecf-3fc1f51f14c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;select2-container select2-container--default select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--above&quot;]/span[@class=&quot;select2-results&quot;]/ul[@id=&quot;select2-sampling_district-results&quot;]/li[@id=&quot;select2-sampling_district-result-opca-73&quot;]</value>
      <webElementGuid>3e04a9e4-c132-4e59-894d-5651731f3bdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-sampling_district-result-opca-73' and (text() = 'Subang' or . = 'Subang')]</value>
      <webElementGuid>bc668ba6-0908-476b-b6bf-89d05d268f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
