<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Kelurahan --</name>
   <tag></tag>
   <elementGuidId>d23d843c-3dc1-4836-96d0-5ff9dff844f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-sampling_village-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sampling_village-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1191eb2a-b2c5-4ae2-ad7d-0742fc4a7106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a67d97fc-6f6c-4698-818c-7b67663bef29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sampling_village-container</value>
      <webElementGuid>7db883c1-e927-419b-832a-c43ea2145246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>eaf314e8-1613-466a-bebe-c9fde27526e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34f08381-2c6b-4168-ba8f-8f2749b3944b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan --</value>
      <webElementGuid>2b0ba181-842a-44d8-8ae2-4579d7e6c045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan --</value>
      <webElementGuid>c0b6df79-46cc-46ae-8fbc-f7861d093ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sampling_village-container&quot;)</value>
      <webElementGuid>93294635-3071-41b7-bbbf-bd465f46d328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sampling_village-container']</value>
      <webElementGuid>bdb44c82-1a3e-4968-b342-cbb48f7c85eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_section_2']/div/div[4]/span/span/span/span</value>
      <webElementGuid>a2e8ac23-91a0-4311-aad4-9a6e2f51a1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::span[4]</value>
      <webElementGuid>7f5a46ae-64d8-432d-aafa-b424cd5dfbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::span[3]</value>
      <webElementGuid>3b2f532b-c841-46ae-82e8-7c63b186e4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span/span/span</value>
      <webElementGuid>e0568d89-5c8f-43dc-9e26-41ca3f156187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sampling_village-container' and @title = '-- Pilih Kelurahan --' and (text() = '-- Pilih Kelurahan --' or . = '-- Pilih Kelurahan --')]</value>
      <webElementGuid>780e12cf-bc67-405b-b067-f567e9a700bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
