<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ZEE</name>
   <tag></tag>
   <elementGuidId>d3f5c636-c248-42e6-b64c-32c9cca35c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-child_product_before-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-child_product_before-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e2586b9c-2b71-4d09-9ddb-e40884b5890b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>986bef6b-c35d-4841-aa67-d3508d9f4dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-child_product_before-container</value>
      <webElementGuid>94bb960d-75c2-4385-bc82-c5cc60648aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3f10fab9-bdec-4434-bd34-7d0b6dd42376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc2386a2-9391-4860-a976-b1a5988e2d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>
                                    ZEE                                </value>
      <webElementGuid>494f8ab1-d5c0-4f3b-b681-d3d04827e9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    ZEE                                </value>
      <webElementGuid>1a5f7339-7298-43c7-a1f0-269649c519a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-child_product_before-container&quot;)</value>
      <webElementGuid>acc305e1-2d5e-4c3a-9eea-ac24234727d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-child_product_before-container']</value>
      <webElementGuid>3a3e83dd-7465-43e1-af3f-d44dbf0fcabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_section_3']/div/div[2]/span/span/span/span</value>
      <webElementGuid>e3601c60-2a19-4711-bd73-04fef73ac735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[4]</value>
      <webElementGuid>5af08959-9d54-434e-a3f0-817ecb83e1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::span[3]</value>
      <webElementGuid>8e982ff3-91f0-46a3-8ed7-e5c3eb8f7557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::span[3]</value>
      <webElementGuid>f3568e84-85c4-4ed0-9ceb-fb54df3ced23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/span/span/span/span</value>
      <webElementGuid>57f44bc5-64d5-46ff-9357-6ff0d8abe1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-child_product_before-container' and @title = '
                                    ZEE                                ' and (text() = '
                                    ZEE                                ' or . = '
                                    ZEE                                ')]</value>
      <webElementGuid>f0937726-df3f-49d0-84b8-8447ae96c85e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
