<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Kecamatan --</name>
   <tag></tag>
   <elementGuidId>783c8703-35a2-4cb8-a0ca-240f4c16df56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-sampling_subdistrict-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sampling_subdistrict-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41c595fb-26d2-473e-adaf-0809897b57d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9b371091-8329-4600-a9de-bbaa8ad7e55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sampling_subdistrict-container</value>
      <webElementGuid>e169cb8a-6971-4ccf-a6a5-308a12f95f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4418c09f-dff2-44bf-9bfe-08a49f27e2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3deb8617-f33f-4fed-9d93-7380e5a5e4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Kecamatan --</value>
      <webElementGuid>af932e22-d1bc-442a-8846-3bdef4863812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kecamatan --</value>
      <webElementGuid>6af15e5a-b282-4ffe-83e2-d7bfa2fbaa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sampling_subdistrict-container&quot;)</value>
      <webElementGuid>f95aeb72-020d-4ac2-8e1a-918ab1878478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sampling_subdistrict-container']</value>
      <webElementGuid>a95d7158-7af6-4c11-9954-c5da96d44cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_section_2']/div/div[3]/span/span/span/span</value>
      <webElementGuid>756123a5-0c22-4caa-a1de-74704cf29811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[4]</value>
      <webElementGuid>5571dbc7-a430-4881-90cf-a57c10e9c075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::span[3]</value>
      <webElementGuid>ebce5175-e9d5-4e95-9106-0cbe65647bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>ff18a8e0-1c33-4756-b1f6-cf54a210fe78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sampling_subdistrict-container' and @title = '-- Pilih Kecamatan --' and (text() = '-- Pilih Kecamatan --' or . = '-- Pilih Kecamatan --')]</value>
      <webElementGuid>fe21dbfc-0b5f-4cca-81fe-a1187acc5cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
