<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kondisi Mama saat ini_parent-status</name>
   <tag></tag>
   <elementGuidId>c2ef6ae1-72e4-406b-963a-c348e88f606f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parent-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parent-status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>639eb40c-1e3a-450f-82e2-33fb1e245d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>49abe690-f586-4db8-9c12-8af6a2bf619e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69b519c1-43f2-410a-9e1d-db8beea2e5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parent-status</value>
      <webElementGuid>356c066e-757f-4628-b203-d6b495831473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kondisi Mama</value>
      <webElementGuid>0636a7ad-3358-4173-88ab-d3cc96a771a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parent-status&quot;)</value>
      <webElementGuid>d7e0864e-aff4-426c-98de-9591cdae5e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parent-status']</value>
      <webElementGuid>4e4a54d6-632c-4d4e-9339-5f63f4836824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motherCondition']/div/div/input[2]</value>
      <webElementGuid>c5010492-b51f-40f8-b9ab-e37fe10b46f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input[2]</value>
      <webElementGuid>74c6b9a6-8f15-4411-9752-d8c4b7256503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'parent-status' and @placeholder = 'Pilih Kondisi Mama']</value>
      <webElementGuid>3fa4bd01-3421-4953-b156-5a2a3787d4a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
