<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_Fullname</name>
   <tag></tag>
   <elementGuidId>536ed6e7-0d86-4f2d-a4fc-05781737f79e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>415bc13e-01fd-4e6f-8703-ad33d5dc1320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>287da1cf-b617-4085-af12-18a046ccab53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Fullname</value>
      <webElementGuid>594018a2-9613-4705-a14f-600da5784a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullname</value>
      <webElementGuid>0f744c7b-5c89-4382-98a1-5e509c952861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2</value>
      <webElementGuid>eb9570b8-a685-4760-a39a-4774958b6dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jawaban</value>
      <webElementGuid>f2c15c83-c7bc-4116-be24-2b2e7b633a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullname&quot;)</value>
      <webElementGuid>f67dd21c-188b-499a-a816-401874379a6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullname']</value>
      <webElementGuid>54815fcf-080e-42aa-bae1-8bd3f57f6a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[2]</value>
      <webElementGuid>5f6215c4-9b73-4eb0-89b4-ceac4e4356e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Fullname' and @id = 'fullname' and @placeholder = 'Jawaban']</value>
      <webElementGuid>d3fb1f12-43b4-45f0-99ac-76c773aa39ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
