<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-qdewlb1nlucp</name>
   <tag></tag>
   <elementGuidId>4c2cc3a8-eae9-47e9-bfa7-87ccf7c149a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-qdewlb1nlucp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-qdewlb1nlucp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4223d16d-7033-44ff-b07e-6ac7cd834b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>96949a6c-cdb0-496e-9a23-7df8f3d0f21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>c90725b8-1ab1-4c29-8359-5f614bde26d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>3b6d0f8d-8697-48b3-9721-ce01c30a4d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a18db832-95f0-44db-a247-4c5cb19b4342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-qdewlb1nlucp</value>
      <webElementGuid>3604be28-7aa4-43cd-9f13-03738505ad9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54938593-d393-45ff-b9fe-b7a5f64688ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3f4dd8f1-41dc-4a31-b481-b21079517af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>5eca2a37-7a82-49f4-b066-cf35dbdcbdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdRYB4pAAAAAGzT2ZowkIBgV7ugXzsjI_ieHmr3&amp;co=aHR0cHM6Ly9tZW1iZXJzaGlwLm51dHJpY2x1Yi5jby5pZDo0NDM.&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=tibm6bc24jno</value>
      <webElementGuid>bdf0aada-d33c-439a-b678-5bd81496e009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-upload-struk&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>a53f1808-ca4f-4433-8a60-5413d4001e7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-qdewlb1nlucp']</value>
      <webElementGuid>120d816e-c724-425d-9325-bb1b40f2d75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-upload-struk']/div/div/iframe</value>
      <webElementGuid>853d956b-8814-4ac3-90cf-20c0d5abd0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c2e0d30d-1efb-4ac9-9343-ed9215fe7170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-qdewlb1nlucp' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdRYB4pAAAAAGzT2ZowkIBgV7ugXzsjI_ieHmr3&amp;co=aHR0cHM6Ly9tZW1iZXJzaGlwLm51dHJpY2x1Yi5jby5pZDo0NDM.&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=tibm6bc24jno']</value>
      <webElementGuid>cf49610d-0bb2-4ed7-9e5a-c01eb0a773d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
