<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cookie_a-7ibwuooc4jtn</name>
   <tag></tag>
   <elementGuidId>d49653cd-3b91-4e39-bbe3-af5c317b8937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-7ibwuooc4jtn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-7ibwuooc4jtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1676ad9a-3dd9-4353-aa6a-a582b2ca92c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>9bf52d1e-e49b-47b2-be13-abff06e85a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>9fbecaf1-8924-441b-b161-219f45d537ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>86729aad-3e8a-4ea5-8d2a-910b79822a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e0066a74-35c3-475a-a5b1-01aa24009878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-7ibwuooc4jtn</value>
      <webElementGuid>a9772bde-2a77-46a0-b768-269fee71db94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0950de76-6e21-44cb-9bab-f1737114456d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>50ad1cfe-9e73-47bf-b64a-b38f9857e5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>889b2206-3b2a-4382-a37e-5d18376b8dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=jphhmdwj7qpj</value>
      <webElementGuid>39dbff6f-82d7-4b88-9e41-b8d8043cf9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-register&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>1436e259-a853-413e-a768-f1424d544e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-7ibwuooc4jtn']</value>
      <webElementGuid>625eebff-4554-4e3b-94e4-b68d65b06504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-register']/div/div/iframe</value>
      <webElementGuid>f901d861-b4b0-4d0c-98e5-5e2e5788d512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3655dd48-8dce-4d57-ba92-446d1108af79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-7ibwuooc4jtn' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=jphhmdwj7qpj']</value>
      <webElementGuid>0ae2f4f9-5b6e-4374-96ee-f611a4c17ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
