<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Kata Sandi_a-rolmlkx06ck6</name>
   <tag></tag>
   <elementGuidId>cca31b94-1c17-4ecd-b299-a77275c42e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-rolmlkx06ck6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-rolmlkx06ck6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d3f9a804-ab2a-4f93-9e29-86f5ff396c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>84dd0fe4-fc91-4851-8d8f-d1b4e47a784a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>9b7f9b96-5c8e-4c0b-9a0d-b391ddc6c6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>77a63408-79ac-46d2-b238-45bab1355abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>efb1f342-42af-45ad-b577-954aa37d8fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-rolmlkx06ck6</value>
      <webElementGuid>acc2043d-d273-45e9-a7e5-576f79ef9176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a9208b5-be40-4e51-b183-778435da5751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c3cdf680-4776-49bb-980c-4c6e69cf1ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>d97eacca-3351-4101-8a88-84ec6894ff28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=qfyj92u6c9j6</value>
      <webElementGuid>4a3f1713-977f-4d7a-9f98-e453a5176a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-login&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>d30f5639-1e04-4027-8ca3-7516c11ef6df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-rolmlkx06ck6']</value>
      <webElementGuid>4ef5740f-accd-4e90-bce6-e0472dbbbd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-login']/div/div/iframe</value>
      <webElementGuid>920061e9-dbb0-4195-bf2d-423b4c95baa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8339e8ea-ae27-4376-b084-a1b9fae32e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-rolmlkx06ck6' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=qfyj92u6c9j6']</value>
      <webElementGuid>c182b852-d780-4824-bd35-7048f9ca9513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
