<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Kata Sandi_a-wucb5dx5440i</name>
   <tag></tag>
   <elementGuidId>d16571f9-932d-47e0-9256-c4c85c60598a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-wucb5dx5440i&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-wucb5dx5440i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d13041df-1b42-44a0-80b0-5759dbfb6395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>dae9bd1a-9471-4ba6-8a42-2df9bd634365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>89ad67dc-aa00-4af1-b900-a3847496f270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>9fe91f77-ef8a-4fa4-b51f-edfb468e2d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>24722b1c-ff04-4ca6-85c1-eb7188321d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-wucb5dx5440i</value>
      <webElementGuid>3d21c21e-b06e-46c3-a5da-11d60c1a53d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d72ffd83-b2f1-42f3-831c-1ed02cd4ac21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e4ea5855-6800-4201-961e-78caa2926020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>db7c7101-12b3-4ba5-8e1d-ecbc0f16e2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=87wjtn4gkxdw</value>
      <webElementGuid>067164af-01ce-43bc-8f8e-77114ecb939a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-login&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>edef28a7-08d1-4dcb-8523-1d8e362d007f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-wucb5dx5440i']</value>
      <webElementGuid>d59a4d1e-e99e-45a2-8f53-39435c965938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-login']/div/div/iframe</value>
      <webElementGuid>8d4fb8e1-8cb1-4789-95ab-e1e8af6c0281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>05f6739e-d058-44c8-9643-99980864b9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-wucb5dx5440i' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=QquE1_MNjnFHgZF4HPsEcf_2&amp;theme=light&amp;size=normal&amp;cb=87wjtn4gkxdw']</value>
      <webElementGuid>8d93f901-f47a-48c6-a40d-03b9e20ad902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
