<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Struk 2_receipt-img</name>
   <tag></tag>
   <elementGuidId>41128d51-4b39-45ad-b03c-10369133b482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receipt-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='receipt-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>251501b2-ab10-4a44-a870-e2fb751edfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>receipt-img</value>
      <webElementGuid>ef523f08-c15f-4c95-9a82-f7cf7cef305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receipt-img</value>
      <webElementGuid>201a5824-cb26-4f9a-ad3c-6366da0d2852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/rrr_images/receipt-submission/click-trigger-upload.png</value>
      <webElementGuid>464dbf27-fe76-42ae-9bc4-87f2f775d7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>fd12405c-f9c6-4a50-99a1-618bad195109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receipt-img&quot;)</value>
      <webElementGuid>f6a5e893-ef3f-4cc7-9af2-5087a6438eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='receipt-img']</value>
      <webElementGuid>8dd0b404-df1b-43d0-a6a9-f3e75fdfa9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upload-receipt']/div[2]/div/div/img</value>
      <webElementGuid>30b9a8f2-0fd6-43ca-94dd-f8d93161313c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='upload'])[6]</value>
      <webElementGuid>28317768-86db-4f91-8ec9-d22f0a5040cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>ceeb3ac5-dbe5-4fa6-a6f7-cf914a74557a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'receipt-img' and @src = '/assets/rrr_images/receipt-submission/click-trigger-upload.png' and @alt = 'upload']</value>
      <webElementGuid>4c0f976d-a589-4e46-98ad-f78b90d1d9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
