<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan Nomor HP_user_credential</name>
   <tag></tag>
   <elementGuidId>337c5635-0ae0-49b8-bc4b-83b031170207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-credential</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-credential']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6097cd8-e6b1-4031-ba8b-51f4e34eeeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f7f46ac-dc51-4db1-af9f-0c3932374b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-credential</value>
      <webElementGuid>de4bb49c-22f4-482b-94da-d473df36b65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_credential</value>
      <webElementGuid>574d5214-6b5a-4601-b1ba-95357c35ca6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>2c3a0229-3b36-42ec-b174-d4b9ae582540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-3</value>
      <webElementGuid>2dcfbe45-29f6-4c6d-a210-f79ed3cf8174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor HP</value>
      <webElementGuid>378e6caa-126c-4d7a-ada9-aefddf257740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-credential&quot;)</value>
      <webElementGuid>3ea1ffb0-e53b-4028-a926-1516d10f640f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-credential']</value>
      <webElementGuid>41e9d0ef-e01d-4fdc-84a5-2732b4fc969e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[3]/div/div/input</value>
      <webElementGuid>63f4a253-71b3-45e8-8939-3195fbd41c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>434d8120-6a03-405b-acee-f1121f599dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user-credential' and @name = 'user_credential' and @placeholder = 'Nomor HP']</value>
      <webElementGuid>d9632e11-9856-4905-85a8-e0e74cab1cbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
