<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cookie_a-u57op8hjub6s</name>
   <tag></tag>
   <elementGuidId>7d9f6db2-8a25-4f30-9561-f44381680b0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-u57op8hjub6s']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-u57op8hjub6s&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b42d3dc0-180b-4450-a443-f9bc74f7d70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>bf1edb8c-7e22-4a6c-a04f-b99bdf1bf901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>c327cb66-dce1-474d-b770-415e3afcf828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>dee7660f-c9d1-40aa-b591-7fbb519a164d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>53ab032d-a0e6-472c-b143-c0ae6922d549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-u57op8hjub6s</value>
      <webElementGuid>dc366564-e5b3-48b8-843b-01926a005a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fad59a3e-dd5a-45a3-a9e8-f46c10d706dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ef5a5e80-9811-4879-9185-2592f847265e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>9d7e8723-cbbf-48e1-b8d7-2fa229df0a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdGt8EoAAAAALIjgtDOjGWT0KSKJnphBtz2Oj4r&amp;co=aHR0cHM6Ly9udXRyaWNsdWIuZXlkZW5kaWdpdGFsLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=u-xcq3POCWFlCr3x8_IPxgPu&amp;theme=light&amp;size=normal&amp;cb=9rx3y6weks4z</value>
      <webElementGuid>f525f3a6-ec09-459b-ad3f-813294582516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-register&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>35b3a958-7a2c-4f95-a996-11775d3ac6f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-u57op8hjub6s']</value>
      <webElementGuid>e3912530-0c00-4fd6-926d-d0d5a6f80fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-register']/div/div/iframe</value>
      <webElementGuid>3f23d0e7-5048-433f-bb85-ebcadeeb853b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6eb17bed-3d93-47c2-aaa2-0eee796c805b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-u57op8hjub6s' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdGt8EoAAAAALIjgtDOjGWT0KSKJnphBtz2Oj4r&amp;co=aHR0cHM6Ly9udXRyaWNsdWIuZXlkZW5kaWdpdGFsLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=u-xcq3POCWFlCr3x8_IPxgPu&amp;theme=light&amp;size=normal&amp;cb=9rx3y6weks4z']</value>
      <webElementGuid>e92b284d-a625-473c-b414-59df5e521960</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
