<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe____st_preview_frame_bpn</name>
   <tag></tag>
   <elementGuidId>6e2905e4-a817-4bfe-8a07-48c2198a6f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__st_fancy_popup']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.__st_preview_frame_bpn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>115662af-ad31-4d7a-ace1-644c2c59ecf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__st_preview_frame_bpn</value>
      <webElementGuid>8faa8aa5-b026-443d-80a0-df955d2af6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4716e451-29a4-4549-abc6-21c62248efbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3714ee28-86ca-4c55-b923-6689d6eb0918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_fancy_popup&quot;)/iframe[@class=&quot;__st_preview_frame_bpn&quot;]</value>
      <webElementGuid>ceb921aa-6ae0-44d6-aba9-1eb389c99fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__st_fancy_popup']/iframe</value>
      <webElementGuid>97098d6a-c0ca-46c9-baf1-07758f7baa4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/iframe</value>
      <webElementGuid>4d0142fa-93b0-426e-b600-49a5044da29a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
