<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir Anak_dp1693475946926</name>
   <tag></tag>
   <elementGuidId>85e87dcd-97c0-4738-ae42-5068603a2f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1693475946926</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1693475946926']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>181f34d4-615a-428d-b9e7-4a5f60c84ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38225fdf-5c3a-4409-880c-dc7ca8e99fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control childBirthday bg-white hasDatepicker</value>
      <webElementGuid>d10566bb-9a13-445e-b8ce-7f3714fe6289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jawaban</value>
      <webElementGuid>087f62fa-afa5-49aa-80b0-c41d5d51133e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1693475946926</value>
      <webElementGuid>a94acdbd-cabf-42c3-a754-2c37b26a0ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1693475946926&quot;)</value>
      <webElementGuid>eaea6003-d8e6-4f9b-940d-a7de16c78891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1693475946926']</value>
      <webElementGuid>09e7db33-7c2a-40e6-93ac-229b180aff56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='childDetailsWrapper']/div/div/div/input</value>
      <webElementGuid>15e1dca9-6b9e-4c85-bd53-94b6748c7af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Lahir Anak'])[1]/following::input[1]</value>
      <webElementGuid>ed0ea612-2b78-48cc-8d6e-a0a887c365b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usia Kehamilan (Minggu)'])[1]/following::input[2]</value>
      <webElementGuid>d0a6be53-7e4e-49d6-9228-6de68f22f198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referal'])[1]/preceding::input[3]</value>
      <webElementGuid>610f6448-e18a-4d7a-bb84-8e291b1226da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Event'])[1]/preceding::input[4]</value>
      <webElementGuid>b1fc0b8c-deaf-4ef7-b53e-529ddbd43f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>e5df6608-6417-4a70-a159-38f79df91da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Jawaban' and @id = 'dp1693475946926']</value>
      <webElementGuid>714fb123-6a7c-433c-85af-6b8f5d228534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
