<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , __st_bpn_no, , ))_notnow</name>
   <tag></tag>
   <elementGuidId>d7833527-fcaa-4709-948c-efc762960db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__st_bpn_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__st_bpn_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75c6c20c-5a54-4afb-9ecf-1ec99237881d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d46a8fc-4bcb-42e8-9bcf-0ee58320e0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notnow</value>
      <webElementGuid>2b781278-6a90-4234-848d-158828299616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__st_bpn_no</value>
      <webElementGuid>428ad33f-40e3-4e53-a31c-5003a3471f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>c7a0f659-9a43-4f77-935a-1e8e8a19ba33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_bpn_no&quot;)</value>
      <webElementGuid>32e2e19c-d3cf-489d-be47-509d49c2f951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Register Nutri/iframe____st_preview_frame_bpn</value>
      <webElementGuid>6b785e1e-3949-4508-b51a-2d34f4d98889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__st_bpn_no']</value>
      <webElementGuid>720852e7-22a7-4909-b84f-bf0de2a92816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bf9e8018-f6ad-4bd1-ad0c-88d266022445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'notnow' and @id = '__st_bpn_no']</value>
      <webElementGuid>161c4003-70ab-4526-bec2-53419dfe5851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
