<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kondisi belum hamil</name>
   <tag></tag>
   <elementGuidId>f1776883-54b6-4bcc-a39b-320b391c8758</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='motherCondition']/div/div/div/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content__stage-mark</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;motherCondition&quot;)/div[@class=&quot;content__card rounded content__input shadow --show-bg-card&quot;]/div[@class=&quot;content__card-text text-center&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-6 col-md-3&quot;]/label[@class=&quot;content__stage&quot;]/div[@class=&quot;content__stage-mark&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>181e8877-c312-470b-8636-cb1e37f2daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content__stage-mark</value>
      <webElementGuid>ea655d1a-71ef-4291-8d7e-72de5d74baab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;motherCondition&quot;)/div[@class=&quot;content__card rounded content__input shadow --show-bg-card&quot;]/div[@class=&quot;content__card-text text-center&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-6 col-md-3&quot;]/label[@class=&quot;content__stage&quot;]/div[@class=&quot;content__stage-mark&quot;]</value>
      <webElementGuid>27c7017b-ef00-4952-964c-450d84e4ce02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motherCondition']/div/div/div/div/label/div</value>
      <webElementGuid>a9a15879-7b04-4935-96df-17d9faf66d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>052169d7-c18d-42ec-8a68-80f43de7fc75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
