<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kondisi belum hamil</name>
   <tag></tag>
   <elementGuidId>f1776883-54b6-4bcc-a39b-320b391c8758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='motherCondition']/div/div/div/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content__stage-mark</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;motherCondition&quot;)/div[@class=&quot;content__card rounded content__input shadow --show-bg-card&quot;]/div[@class=&quot;content__card-text text-center&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-6 col-md-3&quot;]/label[@class=&quot;content__stage&quot;]/div[@class=&quot;content__stage-mark&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01091969-9420-494a-a544-2f0a93c900ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content__stage-mark</value>
      <webElementGuid>084bad91-21d7-481e-8a51-492d00d71272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;motherCondition&quot;)/div[@class=&quot;content__card rounded content__input shadow --show-bg-card&quot;]/div[@class=&quot;content__card-text text-center&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-6 col-md-3&quot;]/label[@class=&quot;content__stage&quot;]/div[@class=&quot;content__stage-mark&quot;]</value>
      <webElementGuid>3d088ce2-43e3-4180-a2d4-3c6f6eed5a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motherCondition']/div/div/div/div/label/div</value>
      <webElementGuid>77c3cf45-4a10-4e23-b316-fff21d560d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>bfe73c12-a2da-4e43-a516-e6c549e27565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
